source 'https://rubygems.org'
ruby   '2.0.0'

gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'haml'
gem 'sass'
gem 'compass'
gem 'newrelic_rpm'
gem 'activerecord'
gem 'activerecord-postgresql-adapter'
gem 'unicorn'
gem 'pg'
gem 'chartkick'
gem 'groupdate'
gem 'awesome_print'
gem 'pry'
gem 'tux'

group :development do
  gem 'shotgun'
  gem 'rubocop'
  gem 'better_errors'
  gem 'binding_of_caller'
end
